### ISSUE TITLE
[General Contract] **Contract Name**

### ISSUE THREAD

**Issue by prajjwaljogdand** [Magickbase/godwoken_explorer#1031]
### Contract Name

BrainiacNft

### Contract Address

0xf670e39fffb100856ebce09f1dd7c69070d6538f

### Compiler Version

v0.8.4

**Comment by Keith-CY** [comment]
Hi @prajjwaljogdand 
The contract name and compiler version have been updated
![image](https://user-images.githubusercontent.com/7271329/194536553-08611c04-ceb3-4912-81f6-68aff6955901.png)

Token in list: https://v1.testnet.gwscan.com/contracts?page=953

Since Brainic is a well-known community project, I also update its 
- logo: ![](https://www.brainiacnfts.com/images/landing/beaniepunk1.png)
- website: https://www.brainiacnfts.com/

Please correct me if logo or website is invalid.
