### ISSUE TITLE
after waiting for a long time, the transaction list shows

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#1114]
url: https://v1.testnet.gwscan.com/account/0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266?tab=transactions
The first time to query the transaction of the account,need a lot of time
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/32102187/198497649-4765c593-5619-4133-b527-7633789ed783.png">

Wait more than 10 seconds ,the transaction list shows
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/32102187/198497555-1db2a0a5-3920-4dd4-a725-ebb934a1676a.png">

**Comment by Naupio** [comment]
use dataloader to solve graphql subfield n-query problem

**Comment by Keith-CY** [comment]
> use dataloader to solve graphql subfield n-query problem

Please add the analysis or detailed reason along with the solution

**Comment by Naupio** [comment]
pr link: #1183

**Comment by Naupio** [comment]
the transaction object has some subfields like 
```
    polyjuice subfield
    polyjuice_creator subfield
    from_account subfield
    to_account subfield
    block subfield
```
which will cause the `transactions` api  query slowly due to`n+1 querys problem`.

there two way the fix this efficiency problem
1. use the `Batching Resolution` by manuls
2. use the `Dataloader`(refer to facebook graphql dataloader)  infrastructure to solve the `n+1` problem automatically

**Comment by Keith-CY** [comment]
Will be optimized by using `Dataloader`, tracked by issue https://github.com/Magickbase/godwoken_explorer/issues/1184 so this one could be closed
