### ISSUE TITLE
State of a revocation button is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1128]
https://user-images.githubusercontent.com/7271329/200217142-475d547c-77eb-4388-bd68-8587ffbb1165.mov

1. Buttons have different states on visiting
![image](https://user-images.githubusercontent.com/7271329/200217195-494e6847-6c5e-46f4-b93d-da031c86f49c.png)

2. Buttons have different states on opening metamask
![image](https://user-images.githubusercontent.com/7271329/200217383-8c8a5209-cfe7-41d0-b893-1ad4f101cf56.png)

**Comment by qiweiii** [comment]
@Keith-CY these are expected
1. as we use wagmi [usePrepareContractWrite](https://wagmi.sh/docs/prepare-hooks/usePrepareContractWrite) to prepare contract write for each button, they will be fetching required info when page refreshes, and depends on network speed, some button may finish fetching earlier than others. And when it's fetching/preparing, we disable the button because it won't work if user click on it.
2. when open mm, the button's state is changed to waiting for user to confirm/reject, and button is disabled, because if use we allow user to click on revoke again, mm will create a duplicated tx. So to prevent user accidentlly comfirm the duplicated tx, we added this state.
