### ISSUE TITLE
[Native ERC20 Token] DGB

### ISSUE THREAD

**Issue by godworkon** [Magickbase/godwoken_explorer#1573]
### Token Name

DGB,The Beggar's Sect Token

### Description

一个有趣的丐帮复建MEME币，持有DGB可以加入歪脖山丐帮奉旨乞讨，参与去中心化社区建设活动。

### Max Supply

5000000000000000

### Website

_Website is building_

### Logo URI

https://s2.loli.net/2024/01/03/PC5oEqJdYSfag6j.jpg

### Contract Address

0x85b62747d3cd7bdaafed6e50f5aa83c4a91268b9

### Code Format

None

**Comment by zmcNotafraid** [comment]
Logo URI is unreadable.Please  change image hosting

**Comment by godworkon** [comment]
![1](https://github.com/Magickbase/godwoken_explorer/assets/155158309/dc852cf0-4459-4aeb-b314-a61e51dd09f9)

**Comment by godworkon** [comment]
Logo URL is:
https://private-user-images.githubusercontent.com/155158309/293893850-dc852cf0-4459-4aeb-b314-a61e51dd09f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzk2MzcsIm5iZiI6MTcwNDI3OTMzNywicGF0aCI6Ii8xNTUxNTgzMDkvMjkzODkzODUwLWRjODUyY2YwLTQ0NTktNGFlYi1iMzE0LWE2MWU1MWRkMDlmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMDU1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWY1ZDA5MTJiY2UzODYxNTQ1ZjZlOGQ4ZmFhZDUxZTQ4NGU4NGEzYzIxNWE2NDQ1NDkyOWEwYzZmYTdkZDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xXEwbV4-t7KSUIl3Q3PqW-DWAyQkeW1Jz179Yyq7zHk
________________________________
发件人: Miles Zhang ***@***.***>
发送时间: 2024年1月3日 17:15
收件人: Magickbase/godwoken_explorer ***@***.***>
抄送: godworkon ***@***.***>; Author ***@***.***>
主题: Re: [Magickbase/godwoken_explorer] [Native ERC20 Token] DGB (Issue #1573)


Logo URI is unreadable.Please change image hosting

―

**Comment by zmcNotafraid** [comment]
This url returns 404 for me.You need to upload image to image hosting such as SM.MS。

**Comment by godworkon** [comment]
URL is：
https://s2.loli.net/2024/01/03/PC5oEqJdYSfag6j.jpg
[https://s2.loli.net/2024/01/03/PC5oEqJdYSfag6j.jpg]


________________________________
发件人: Miles Zhang ***@***.***>
发送时间: 2024年1月3日 19:39
收件人: Magickbase/godwoken_explorer ***@***.***>
抄送: godworkon ***@***.***>; Author ***@***.***>
主题: Re: [Magickbase/godwoken_explorer] [Native ERC20 Token] DGB (Issue #1573)


This url returns 404 for me.You need to upload image to image hosting such as SM.MS。

―

**Comment by zmcNotafraid** [comment]
It worked. https://v1.gwscan.com/zh-CN/token/13012

**Comment by godworkon** [comment]
why update comment is not work?

**Comment by Keith-CY** [comment]
> why update comment is not work?

Hi @godworkon, I didn't get `why update comment is not work`.

If you were mentioning that the `token name` displayed on GwScan `DaGouBang` is different from that in the top message `DGB,The Beggar's Sect Token`, it's because the `token name` has been defined in the contract and parsed from on-chain data.

You may verify the contract by clicking `Verify by Sourcify` at https://v1.gwscan.com/account/0x85b62747d3cd7bdaafed6e50f5aa83c4a91268b9 and once the contract is verified, it's contract method will be available at this page and the `token name` can be decoded on the page. E.g. getting token name of `BRAIN` at https://v1.gwscan.com/account/0x0278fc024923b81df3e76960c978c429c2cfb28e?tab=contract

<img width="1218" alt="image" src="https://github.com/Magickbase/godwoken_explorer/assets/7271329/c502e62c-a782-4cdf-b166-1ddb09567b6f">

**Comment by godworkon** [comment]
我更新了上面关于代币的内容，但是在GwScan上面没有更新成最新内容，如何解决这个问题呢？

**Comment by zmcNotafraid** [comment]
> 我更新了上面关于代币的内容，但是在GwScan上面没有更新成最新内容，如何解决这个问题呢？

I missed it.Now it's updated.

**Comment by godworkon** [comment]
perfect,thanks.
________________________________
发件人: Miles Zhang ***@***.***>
发送时间: 2024年1月4日 8:49
收件人: Magickbase/godwoken_explorer ***@***.***>
抄送: godworkon ***@***.***>; Author ***@***.***>
主题: Re: [Magickbase/godwoken_explorer] [Native ERC20 Token] DGB (Issue #1573)


It worked. https://v1.gwscan.com/zh-CN/token/13012

―
