### ISSUE TITLE
[v0] ckb(0x9d9599c41383d7009c2093319d576aa6f89a4449)  verify contract is fake 

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#376]
https://gwscan.com/account/0x9d9599c41383d7009c2093319d576aa6f89a4449?tab=contract

contract is fake
```
function decimals() public view virtual override returns (uint8) {
        return 18;
    }
```
invoke method decimals
![image](https://user-images.githubusercontent.com/32102187/163325590-426ce4a1-f12d-4cd5-8c02-1874fdc8b5c6.png)

**Comment by Keith-CY** [comment]
Contracts in GwScan are not verified, that's why we call them registered contracts.

And there are plenty of exceptions, like CKB Contract, WCKB Contract, they have decimal = 18 in contract, but the actual decimal is 8.

It's indeed a confusing problem, any advice on this? @Flouse

Ref: https://github.com/nervosnet/godwoken_explorer/issues/329

**Comment by Keith-CY** [comment]
> ## User-defined decimals is supported.
> see: [https://github.com/nervosnetwork/godwoken-polyjuice/blob/main/solidity/erc20/SudtERC20Proxy_UserDefinedDecimals.sol#L155](https://github.com/nervosnetwork/godwoken-polyjuice/blob/main/solidity/erc20/SudtERC20Proxy_UserDefinedDecimals.sol?rgh-link-date=2022-04-15T01%3A38%3A38Z#L155)
> 
> Hence, developers could deploy a sUDT_ERC20_Proxy with `decimals` matching the related token.
> 
> Here is the [code example](https://github.com/nervosnetwork/layer2-evm-documentation/blob/master/code-examples/5-erc20-proxy/index.js?rgh-link-date=2022-04-15T01%3A38%3A38Z#L11-L34) written by @Kuzirashi .

Gotcha, I'll confirm it with Yokai Team

**Comment by Keith-CY** [comment]
We've come to a conclusion.

Since there're two kinds of bridge token contracts and not recorded in GitHub, we cannot find out their own contract version.

To avoid confusion, I'll go through all bridge token contracts and remove their source code if decimal is incorrect. @gpBlockchain 

We'll stick to the registration workflow in v1 so this case won't happen again.

**Comment by Keith-CY** [comment]
Source codes of these contracts are removed

BCH: https://www.gwscan.com/account/0x7e9b67663254ec92e7a1541d9ecf38634082c79b?tab=contract
BTC: https://www.gwscan.com/account/0x0bd2ae370ed96d0da4d96b648c8a64ffac038264?tab=contract
CKB: https://www.gwscan.com/account/0x9d9599c41383d7009c2093319d576aa6f89a4449?tab=contract
dCKB: https://www.gwscan.com/account/0x53a1964a163f64da59efe6a802e35b5529d078e2?tab=contract
DOT: https://www.gwscan.com/account/0x73cf05f15fcaf981bc6b83022f1976e4a18d50da?tab=contract
TAI: https://www.gwscan.com/account/0xf4187511d43b90751a28b6811d13afb49bef8452?tab=contract
LTO: https://www.gwscan.com/account/0x572136bfd2c85877cf53ee65d8f2b367bf52dc5e?tab=contract
TRX: https://www.gwscan.com/account/0xaa0e6c6dea0119cdd78666b1e8192bb4583dff40?tab=contract
USDC: https://www.gwscan.com/account/0xc3b946c53e2e62200515d284249f2a91d9df7954?tab=contract
USDT: https://www.gwscan.com/account/0x07a388453944bb54be709ae505f14aeb5d5cbb2c?tab=contract
