### ISSUE TITLE
[feat] Search token in token list

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#697]
e.g. How to locate USDC in https://v1.gwscan.com/tokens/bridge ?

![image](https://user-images.githubusercontent.com/1297478/177141635-69171359-66a2-49a1-a659-250416781998.png)

**Comment by Keith-CY** [comment]
Will be enabled with this feature

**Comment by Keith-CY** [comment]
All APIs are ready, will be updated in front-end by 08/03

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/391

**Comment by Flouse** [comment]
When you search `busd`, it jump to `https://v1.gwscan.com/token/246?search=busd` without a search result list.
Is that an expected behavior?

**Comment by Keith-CY** [comment]
> When you search `busd`, GwScan jumps to `https://v1.gwscan.com/token/246?search=busd` without a search result list. Is that an expected behavior?

Nope, because there're many tokens having the same name or symbol and we cannot decide which one to go, `token name/token symbol` will be removed from the main search field and users could use a filter in the token list page to limit the targets https://v1.gwscan.com/tokens/bridge?type=bridge&name=usdc

**Comment by FrederLu** [comment]
Link https://github.com/Magickbase/godwoken_explorer/issues/839#issuecomment-1210271318，verified.
