### ISSUE TITLE
There are discrepancies between the mainnet page and the new UI.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#844]
1、[Transaction Info](https://v1.gwscan.com/tx/0x750220547048d897aae906840a731fbaeeb778a6e670ede2043d6a49814ba779?tab=logs) page logs are empty and lack pictures.
----------------------------------------------------------------------------------------------------------------------------------
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/25676576/183333759-d45ea7af-fd70-4529-8263-9846ed25a84b.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/25676576/183333964-20a5db35-5759-4ffb-84a8-55cbaf5672c5.png">

----------------------------------------------------------------------------------------------------------------------------------
2、When the Transactions and Bridged Transfers in the [Block page](https://v1.gwscan.com/block/0xf4c4712cd96b85e1efbf447f0ea8272a1d2d2c10e2202176272f7c0663f37293) are empty, it prompts that the text and icons need to be modified.
----------------------------------------------------------------------------------------------------------------------------------
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/25676576/183334882-f58caf19-5590-42d5-bd71-16da35ed89c4.png">
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/25676576/183335657-ab3eeaf6-5562-476b-9df9-f544cff63388.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/25676576/183335491-866b03fb-22fd-40f8-af68-11e5410c08e7.png">

----------------------------------------------------------------------------------------------------------------------------------
3、[Blocks](https://v1.gwscan.com/blocks) needs to use cursor pagination like [transactions](https://v1.gwscan.com/txs).
----------------------------------------------------------------------------------------------------------------------------------
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/25676576/183349697-1f6d4ca7-4722-44ef-8ed6-14c78eb0fbb1.png">
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/25676576/183349429-bec12248-11e8-48df-9d14-c73a35cbeead.png">
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/25676576/183349491-56ca2447-f8c2-472c-ac36-d0675572055e.png">
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/25676576/183349540-3d1d18ca-d3b3-43ac-827d-02a3b0f82f10.png">

----------------------------------------------------------------------------------------------------------------------------------
4、The type icon is missing from the value column in the [transactions list](https://v1.gwscan.com/txs?page_size=50&after=g3QAAAADZAAMYmxvY2tfbnVtYmVyYgABKsBkAARoYXNodAAAAANkAApfX3N0cnVjdF9fZAAiRWxpeGlyLkdvZHdva2VuRXhwbG9yZXIuQ2hhaW4uSGFzaGQACmJ5dGVfY291bnRhIGQABWJ5dGVzbQAAACCl7kMsmuOk7RRk4I-z_bAxtjZd1I2VaFgYx9hJ1RGKNGQABWluZGV4YQA%3D).
----------------------------------------------------------------------------------------------------------------------------------
<img width="947" alt="image" src="https://user-images.githubusercontent.com/25676576/183350249-273e786d-6edb-48de-82d2-198d06ed1db2.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/25676576/183350169-585636f0-30a9-4103-948c-3dedab130a39.png">

----------------------------------------------------------------------------------------------------------------------------------
5、The value in the transactions tab of the [Block details page](https://v1.gwscan.com/block/0x3dccd6329901ab373d9bd94fa9d62c828c0a5cf41b47f8e19029db4c4744deff) is missing the type icon.(
Similar to point 4 above.)
----------------------------------------------------------------------------------------------------------------------------------
<img width="803" alt="image" src="https://user-images.githubusercontent.com/25676576/183354966-5c37b1d6-34fa-4f73-8d4e-eac021111132.png">
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/25676576/183355223-e12444aa-e0c4-4342-87f5-4e1861d7eda9.png">

----------------------------------------------------------------------------------------------------------------------------------
6、Take the [user account](https://v1.gwscan.com/account/0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6?tab=transactions) as an example, the account page transactions and ERC20 Transfers the Method column information is missing in the tab，and the icon of block, age, from, and to must be filtered.
----------------------------------------------------------------------------------------------------------------------------------
<img width="847" alt="image" src="https://user-images.githubusercontent.com/25676576/183381496-68892c38-58a1-48a2-b946-33502349a46c.png">
<img width="658" alt="image" src="https://user-images.githubusercontent.com/25676576/183381638-a4936f6a-bd17-4f31-adbb-5d9053f1d6aa.png">

----------------------------------------------------------------------------------------------------------------------------------
7、The empty state prompt information in the user defined assets tab of the [contract account page](https://v1.gwscan.com/account/0x7538c85cae4e4673253ffd2568c1f1b48a71558a?tab=assets) needs to be displayed in the center.
----------------------------------------------------------------------------------------------------------------------------------
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/25676576/183384569-03e2cf57-1b31-4af4-9ed3-fd3ac73786c6.png">

----------------------------------------------------------------------------------------------------------------------------------
8、The token, circulating supply, and holders of the token list(bridge and native) lack sorting icons.
----------------------------------------------------------------------------------------------------------------------------------

<img width="943" alt="image" src="https://user-images.githubusercontent.com/25676576/183391831-42d702a4-d61b-4c4a-ad32-5cc7e4f82675.png">
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/25676576/183392009-7c6a6ff3-eab3-46d9-b534-ff62cec37ff1.png">

----------------------------------------------------------------------------------------------------------------------------------
9、The holders tab of the token details page is not yet a cursor pagination.
----------------------------------------------------------------------------------------------------------------------------------
bridge token https://v1.gwscan.com/token/33?tab=holders
native token https://v1.gwscan.com/token/264?tab=holders

----------------------------------------------------------------------------------------------------------------------------------
10、Registered contracts page balance and txn need to sort icons.
----------------------------------------------------------------------------------------------------------------------------------
<img width="914" alt="image" src="https://user-images.githubusercontent.com/25676576/183400353-7bc1b81d-d1ff-41c7-8fac-29bb51374d99.png">
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/25676576/183399975-1fc845c3-adad-46d9-83ef-f7d36996be85.png">

----------------------------------------------------------------------------------------------------------------------------------
11、In the [contract account](https://v1.gwscan.com/address/0xf4b5cd842e1962ca5b59327fe4bbf5b845c18669), when there is only a small amount of information in basic info, there is an extra blank in the overview block.
----------------------------------------------------------------------------------------------------------------------------------
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/25676576/183401053-1755d98d-56b5-4769-9884-d7603b598298.png">

----------------------------------------------------------------------------------------------------------------------------------

**Comment by Keith-CY** [comment]
1、[Transaction Info](https://v1.gwscan.com/tx/0x750220547048d897aae906840a731fbaeeb778a6e670ede2043d6a49814ba779?tab=logs) page logs are empty and lack pictures.
2、When the Transactions and Bridged Transfers in the [Block page](https://v1.gwscan.com/block/0xf4c4712cd96b85e1efbf447f0ea8272a1d2d2c10e2202176272f7c0663f37293) are empty, it prompts that the text and icons need to be modified.
7、The empty state prompt information in the user defined assets tab of the [contract account page](https://v1.gwscan.com/account/0x7538c85cae4e4673253ffd2568c1f1b48a71558a?tab=assets) needs to be displayed in the center.

Are fixed in https://github.com/Magickbase/godwoken-explorer-ui/pull/417

3、[Blocks](https://v1.gwscan.com/blocks) needs to use cursor pagination like [transactions](https://v1.gwscan.com/txs). will be updated when graphql API is adopted in this page

4、The type icon is missing from the value column in the [transactions list](https://v1.gwscan.com/txs?page_size=50&after=g3QAAAADZAAMYmxvY2tfbnVtYmVyYgABKsBkAARoYXNodAAAAANkAApfX3N0cnVjdF9fZAAiRWxpeGlyLkdvZHdva2VuRXhwbG9yZXIuQ2hhaW4uSGFzaGQACmJ5dGVfY291bnRhIGQABWJ5dGVzbQAAACCl7kMsmuOk7RRk4I-z_bAxtjZd1I2VaFgYx9hJ1RGKNGQABWluZGV4YQA%3D).
5、The value in the transactions tab of the [Block details page](https://v1.gwscan.com/block/0x3dccd6329901ab373d9bd94fa9d62c828c0a5cf41b47f8e19029db4c4744deff) is missing the type icon.(

Transfer direction exists only in account page because it requires a viewer to determine the direction. https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU?node-id=3205:19091#241485996


6、Take the [user account](https://v1.gwscan.com/account/0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6?tab=transactions) as an example, the account page transactions and ERC20 Transfers the Method column information is missing in the tab，and the icon of block, age, from, and to must be filtered.
8、The token, circulating supply, and holders of the token list(bridge and native) lack sorting icons.
9、The holders tab of the token details page is not yet a cursor pagination.
10、Registered contracts page balance and txn need to sort icons.

Features to be implemented, also related to the adoption of graphql APIs

https://github.com/Magickbase/godwoken_explorer/issues/556
https://github.com/Magickbase/godwoken_explorer/issues/835

11、In the [contract account](https://v1.gwscan.com/address/0xf4b5cd842e1962ca5b59327fe4bbf5b845c18669), when there is only a small amount of information in basic info, there is an extra blank in the overview block.

Two fields( deployer, deploy tx hash) are missing in the API, should be fixed along with https://github.com/Magickbase/godwoken_explorer/issues/627#issuecomment-1195844867

**Comment by FrederLu** [comment]
The problem association in the issue has been confirmed.
