### ISSUE TITLE
 The `method_id` data of the interface is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#894]
"address":"0x39784ddab654e8469498cb24ead628e6df644ec9"

https://godwoken-explorer-khpf27vy6-nervosnet.vercel.app/account/0x39784ddab654e8469498cb24ead628e6df644ec9?page_size=50&after=g3QAAAADZAAMYmxvY2tfbnVtYmVyYgAEInBkAARoYXNodAAAAANkAApfX3N0cnVjdF9fZAAiRWxpeGlyLkdvZHdva2VuRXhwbG9yZXIuQ2hhaW4uSGFzaGQACmJ5dGVfY291bnRhIGQABWJ5dGVzbQAAACBplPC_x5VUTGHFJqQCvuI-DcF2gUqoJV8DeyTKVXyAzmQABWluZGV4YQA%3D

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/25676576/186615312-9965b2c1-ee2d-4c83-8f9f-3e682114814a.png">

The method_id of the interface is shown as "0x".

**Comment by Naupio** [comment]
`method id` decode from `input` data, seems those transactions's input value is `0x`

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/12268276/186678675-2f8f4fcc-4d95-48f8-942f-7a5fd3901592.png">

**Comment by Keith-CY** [comment]
> `method id` decode from `input` data, seems those transactions's input value is `0x` @FrederLu @Keith-CY
> 
> <img alt="image" width="1246" src="https://user-images.githubusercontent.com/12268276/186678675-2f8f4fcc-4d95-48f8-942f-7a5fd3901592.png">

`Method Id` refers to the first 8 bytes of input(`0x | method id | arguments`, in this case, method id should be `null`(because the first 8 bytes are empty). Furthermore, if `input` has less than 8 bytes, it's not a contract call and `method id` should be `null`, too. Furthermore again 🙈 , if `to` in the tx is not a contract account, `method id` should be `null`, too.

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken_explorer/pull/962

**Comment by FrederLu** [comment]
Verified.
